### PR TITLE
Backport type stub as well

### PR DESCRIPTION
**Pull request by tmke8**
So that static type checkers know how it works.

I hope I put it in the right location.

Type stubs copied from here: https://github.com/python/typeshed/blob/0480550fc3643f254b7a8d578d497896db0fadbb/stdlib/enum.pyi#L249

### CODE REVIEW

**Comment by clbarnes** [comment]
Thanks for the contribution!

I haven't used py.typed before - it looks like it's more involved in data validation rather than type checking? Does that divert at all from the core point of this backport - to behave the same as the stdlib?

**Comment by tmke8** [comment]
So, according to [the documentation](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages), a `py.typed` file shouldn't be needed if no inline type annotations are needed. However, after a lot of tinkering, I couldn't make it work without a `py.typed` file. Mypy then always said
```
test.py:2: error: Library stubs not installed for "backports.strenum" (or incompatible with Python 3.9)
test.py:2: note: Hint: "python3 -m pip install types-backports"
test.py:2: note: (or run "mypy --install-types" to install all missing stub packages)
test.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

I don't think I've ever heard this file being involved in data validation? Do you have a link? My understanding is that it's just an empty file that's a signal to a static type checker that this package has type annotations. Without this marker, the static type checker will not bother to look for type annotations.

However, during my testing I also noticed that the stub file should be called `__init__.pyi` and not `strenum.pyi`, so I fixed that.

**Comment by clbarnes** [comment]
> I don't think I've ever heard this file being involved in data validation?

My mistake, I confused it with the `typed` library on PyPI. Thanks for the note about the marker file, sounds like I have some other packages to throw that into!

Is the separate pyi file necessary or could those annotations go into the implementation?

**Comment by tmke8** [comment]
Ah, no, they could definitely go into the implementation. I just thought you might want to keep it as it is in the standard library, where implementation and type annotations are separate. But I can definitely merge them!

**Pull request closed without merging**
