### PR TITLE
Add inline type annotations (and py.typed file)

### PR DESCRIPTION
**Pull request by tmke8**
Replaces #4 

I had to add `@staticmethod` to `_generate_next_value_` because of a known limitation in type checkers:

- https://github.com/python/mypy/issues/7591
- https://github.com/microsoft/pyright/issues/800

If you know have some code like this:
```python
from enum import auto
from backports.strenum import StrEnum

class phy(StrEnum):
    pi = auto()
    tau = "Tau"

reveal_type(phy.pi.value)
reveal_type(phy.tau.value)
```
Then pyright outputs:
```
  test.py:8:13 - information: Type of "phy.pi.value" is "str"
  test.py:9:13 - information: Type of "phy.tau.value" is "Literal['Tau']"
```
which is perfect.

Mypy unfortunately seems to be getting confused by the custom `__new__` function. If I comment out `__new__` in `StrEnum`, then mypy is successful as well:
```
test.py:8: note: Revealed type is "builtins.str"
test.py:9: note: Revealed type is "Literal['Tau']?"
```
However, with the `__new__` function, I think mypy thinks all bets are off concerning the behavior of the Enum, and then it falls back to reporting `Any`:
```
test.py:8: note: Revealed type is "Any"
test.py:9: note: Revealed type is "Any"
```

Anyway, I'd argue this is a mypy bug and doesn't matter that much.

### CODE REVIEW

**Comment by clbarnes** [comment]
Thanks! It's a shame that mypy doesn't play nice as that's probably the biggest type checker and the one preferred by some popular editors. I think that you're right that this does everything it can and will merge, but could you distil the remaining problem into an issue we can leave up for informational purposes?

I probably won't make a release until 3.11 comes out (until then this library isn't exactly a backport :sweat_smile: ) but good to get the ducks in a row!

**Comment by oleksiis-lyft** [comment]
@clbarnes @thomkeh python3.11 is released, can this package be released too? On pypi I see 2021 version

**Comment by clbarnes** [comment]
Yes, I did start updating it for the new version but wanted to backport it all the way to 3.7. The problem is there are some other changes to the stdlib in that time, so it might be a case of *mainly* behaving like the 3.11 version rather than being a perfect copy. In an ideal world I'd replicate all the unit tests from stdlib for it as well but they're kind of nightmare to work through as well!

**Comment by oleksiis-lyft** [comment]
@clbarnes Oh, that sounds like a ton of work. I wanted to get this particular PR in pypi so mypy doesn't complain

**Pull request merged**
