### PR TITLE
Improve type annotations

### PR DESCRIPTION
**Pull request by monosans**
Adapted from [typeshed](https://github.com/python/typeshed/blob/5cd7892f365797bcfaac31118dba1b6b7cf9e992/stdlib/enum.pyi#L252)

### CODE REVIEW

**Comment by clbarnes** [comment]
Thanks for the contribution! I'm not sure I like boxing most of the class' functionality into an `else` statement - could this be achieved with a `.pyi` stub file instead?

**Comment by clbarnes** [comment]
Thanks for the changes. Do you know what effect this will have when using the library? Is there anything the stub file (/ former `if TYPE_CHECKING` implementation) can do which the existing annotations can't?

**Comment by monosans** [comment]
```python
class Foo(StrEnum):
    A = ""


reveal_type(Foo.A._value_)
reveal_type(Foo.A.value)
```

Mypy reveals them both as `Any` instead of `str` without these changes.

---

Also, these changes fix the signature of the StrEnum call:

Before

image

After

image

**Comment by clbarnes** [comment]
Thanks for looking into it - last question, are the new types consistent with what you get from the standard library in python 3.11? If so, I'll merge.

**Comment by monosans** [comment]
> are the new types consistent with what you get from the standard library in python 3.11?

Yes

**Comment by clbarnes** [comment]
[Released](https://pypi.org/project/backports.strenum/)! Thanks again.

**Pull request merged**
